name : Test Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup docker compose
        uses: docker/setup-compose-action@v2

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./.env.example ./.env

      - name: Run Test Script
        run: chmod u+x ./scripts/run-integration.sh && npm run test:integration    
