name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Display Docker version
        run: docker --version

      - name: Display Docker Compose version
        run: docker-compose --version

      - name: Copy .env.example to .env
        run: cp ./.env.example ./.env

      - name: Run Test Script
        run: |
          chmod u+x ./scripts/run-integration.sh
          npm run test:integration
